export const GET_TASKS_PENDING = 'GET_TASKS_PENDING';
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';
export const GET_TASKS_FAILURE = 'GET_TASKS_FAILURE';
export const GET_TASKS_FULFILL = 'GET_TASKS_FULFILL';
