export const GET_TASKS_PENDING = 'GET_TASKS_PENDING';
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';
export const GET_TASKS_FAILURE = 'GET_TASKS_FAILURE';
export const GET_TASKS_FULFILL = 'GET_TASKS_FULFILL';

export const ADD_TASKS_PENDING = 'ADD_TASKS_PENDING';
export const ADD_TASKS_SUCCESS = 'ADD_TASKS_SUCCESS';
export const ADD_TASKS_FAILURE = 'ADD_TASKS_FAILURE';
export const ADD_TASKS_FULFILL = 'ADD_TASKS_FULFILL';

export const UPDATE_TASKS_PENDING = 'UPDATE_TASKS_PENDING';
export const UPDATE_TASKS_SUCCESS = 'UPDATE_TASKS_SUCCESS';
export const UPDATE_TASKS_FAILURE = 'UPDATE_TASKS_FAILURE';
export const UPDATE_TASKS_FULFILL = 'UPDATE_TASKS_FULFILL';

export const DELETE_TASKS_PENDING = 'DELETE_TASKS_PENDING';
export const DELETE_TASKS_SUCCESS = 'DELETE_TASKS_SUCCESS';
export const DELETE_TASKS_FAILURE = 'DELETE_TASKS_FAILURE';
export const DELETE_TASKS_FULFILL = 'DELETE_TASKS_FULFILL';
